### ISSUE TITLE
Keycloak module injects wrong html code into index.html

### ISSUE THREAD

**Issue by werenall** [magnetcoop/hydrogen.duct-template#11]
We make double closure of the script pasted below:
```html
<script src="https://cdn.jsdelivr.net/npm/keycloak-js@6.0.1/dist/keycloak.min.js"
                integrity="sha256-uEsEdiE0XWq07PviSqsGRPdLYHtHk0XsN9+2HsKFXP8="
                crossorigin="anonymous"></script></script>
```

**Comment by iarenaza** [comment]
What does "make double closure of the script" mean? I'm a bit lost here (and don't see anything bad with those two lines)

**Comment by werenall** [comment]
I open a script tag only once, but close it twice `</script></script>`

**Comment by iarenaza** [comment]
Ooooh, now I see it (embarrassed)
