### ISSUE TITLE
Landing page doesn't have a theme

### ISSUE THREAD

**Issue by lucassousaf** [magnetcoop/hydrogen.duct-template#19]
The landing page provided by the template doesn't have any theme assigned. The reason behind this is:
1 - Landing is independent from main application component
2 - We only apply theming to the latter

We thought that landing shouldn't have any theming at all but the current approach for generic CSS classes is using theming to change their `color` and `background-color`. Therefore generic elements like buttons will have their styling changed depending on the theme.

**Comment by werenall** [comment]
We can just hardcode the style in landing to use _the main one_, no?

**Comment by lucassousaf** [comment]
Yes, I think so.
