### ISSUE TITLE
Externs files reorganization.

### ISSUE THREAD

**Issue by iarenaza** [magnetcoop/hydrogen.duct-template#2]
A few weeks ago we decided to split the externs definition files into individual files (one per library/external service). In fact, we do so in oksol (https://bitbucket.org/magnet-coop/oksol/src/master/app/src/oksol/client/foreign-libs/externs/).

We should also be doing things this way in hydrogen.duct-template. Right now we have Cognito externs in the "global" externs file (https://github.com/magnetcoop/hydrogen.duct-template/blob/master/resources/core/cljs/externs.js#L31-L50). And that file is in the same directory as the regular front-end files, and not in a sub directory (./foreign-libs/externs/) like we do in oksol.

**Comment by werenall** [comment]
The extern file mentioned has externs both for cognito and core module. Apart from extracting individual files from that we also have to add one more extern file for keycloak module. A quick sketch of it:

```
goog.provide('Keycloak');
var Keycloak = function () {};
var keycloak = function() {};
keycloak.init = function (initOptions) {};
keycloak.success = function (options) {};
keycloak.error = function (options) {};
keycloak.login = function (options) {};
keycloak.createLoginUrl = function(options) {};
keycloak.logout = function(options) {};
keycloak.createLogoutUrl = function(options) {};
keycloak.register = function (options) {};
keycloak.createRegisterUrl = function(options) {};
keycloak.createAccountUrl = function(options) {};
keycloak.accountManagement = function() {};
keycloak.hasRealmRole = function (role) {};
keycloak.hasResourceRole = function(role, resource) {};
keycloak.loadUserProfile = function() {};
keycloak.loadUserInfo = function() {};
keycloak.isTokenExpired = function(minValidity) {};
keycloak.updateToken = function(minValidity) {};
keycloak.clearToken = function() {};

keycloak.idToken;
```
