### ISSUE TITLE
[ADR required] Path to migrations vs explicit listing of migrations

### ISSUE THREAD

**Issue by werenall** [magnetcoop/hydrogen.duct-template#35]
In some of our projects we configure ragtime migrations by explicitly defining each migration like so:
```edn
{:duct.migrator/ragtime
 {:database   #ig/ref :duct.database/sql
  :logger     #ig/ref :duct/logger
  :strategy   :rebase
  :migrations [#ig/ref :foo.migration/create-foo-table]
  :migrations-table "ragtime_migrations"}}

{[:duct.migrator.ragtime/sql :foo.migration/create-foo-table]
 {:up   [#duct/resource "migrations/foo.up.sql"]
  :down [#duct/resource "migrations/foo.down.sql"]}}
```

Is others, however, we use the sugar to include all migrations found in a path:
```edn
{:duct.migrator/ragtime
 {:database   #ig/ref :duct.database/sql
  :logger     #ig/ref :duct/logger
  :strategy   :rebase
  :migrations [#ig/ref :foo.migrations/dev
               #ig/ref :foo.migrations/prod]}

 [:duct.migrator.ragtime/resources :foo.migrations/dev]
 {:path "dev/migrations"}

 [:duct.migrator.ragtime/resources :foo.migrations/prod]
 {:path "prod/migrations"}}
```

This is useful, yes. But it has some serious downsides:
1. It's harder to catch a conflict when 2 developers push new migrations. While if we'd be using explicit `:migrations []` listing then there will be obvious code conflicts.
2. There is a problem of partial changes being applied and the other few changes failing by erroneous line within a single migration file. Doing explicit listing treats a file like a transaction.

That all said, we should seriously consider tweaking this template so that explicit listing is encouraged.

**Comment by werenall** [comment]
Remember to create an ADR entry for that issue!

**Comment by iarenaza** [comment]
Pasting this internal discussion here, so we don't forget about it.

There is an orthogonal issue that is related to this. The development migrations always go at the beginning of the migrations list (or at the end, depending on the order you specify in the `:migrations` key). But once you have at least one production migration applied and you need to add a new for development (or vice-versa, depending on the order specified in `:migrations`), it fails. It expects to add the new development migration after the last development one (and before any of the production ones) and it can't (the first production migration is already at that position).

Changing `:duct.migrator/ragtime`in `config.edn` to:

```clj
  [:duct.migrator/ragtime :smartg/prod]
  {:database #ig/ref :duct.database/sql
   :logger #ig/ref :duct/logger
   :strategy :raise-error
   :migrations [#ig/ref :smartg.migrations/prod]}
```

and `[:duct.migrator/ragtime :smartg/dev]` in `dev.edn` to:

```clj
 [:duct.migrator/ragtime :smartg/dev]
 {:database #ig/ref :duct.database/sql
  :logger #ig/ref :duct/logger
  :migrations-table "ragtime_migrations_dev"
  :migrations [#ig/ref :smartg.migrations/dev]
  :fake-dependency-to-force-initialization-order #ig/ref [:duct.migrator/ragtime :smartg/prod]}
```

Allows us to send the development migrations to another table, so they don't interfere/mix with the production ones. We also need to add a fake dependency in ` [:duct.migrator/ragtime :smartg/dev]` (that `:duct.migration/ragtime` library completely ignores) to force the order of migrations application.

**Comment by andercarrera** [comment]
After an internal discussion and voting we have decided to use explicit listing of migrations and separate migration tables for production and development. We will shortly add the corresponding ADR and change the template accordingly.
